smaranjitghose/doc2pen

- assets/css/style.css
ss: 
The contact page gets messed due to the name of classes and done little padding in the footer.
> Minor bugs

- index.html
When I checked the code, turns out that jQuery is imported before Bootstrap. After I swapped the position, it loads up correctly.
Here is a working video: [Click here](https://streamable.com/4detpn)
This fixes #211
> Fix the Sidenav to be Opened

- assets/css/style.css
> Fixed "Team members profile pictures were not showing"

- assets/css/editor.css
- assets/css/style.css
- index.html
Fixes: #267 
1. Added id to the contact form in index.html
2. Selected and styled the contact form using the id
3. Removed unncessary code from editor.css
Bug was there because the slider inputs are declared inside a form element and the contact form was also inside the form element, and the contact form was styled using the tag name not by any id, which results in styling of both "contact form" and "slider inputs" using same styles. Now the bug is fixed because the contact form is styled using the id.
@smaranjitghose if you need styling on the background of input sliders then please let me know. I'll add it.
> Background overflow bug

- assets/css/editor.css
Fixes:#345 Download drop-down in the "Editor" section not working properly 
Before:
after:
> fixed download drop-down

- assets/css/style.css
with the reference to the discussion on PR #374 (fixed download drop-down) for issue #345. 
Hover effect removed from the navbar of both pages
***before:***
***after:***
> Removed hove effect from navbar

- src/App.js
- src/components/Header/Header.js
- src/pages/Sketch/Sketch.js
- src/pages/Sketch/Sketch.module.css
- src/pages/Sketch/components/Canvas.js
- src/pages/Sketch/components/Canvas.module.css
Issue #400 
✨ Sketch Page Implemented
1. Header Updated
2. Routes Added for Sketch Page
3. Sketch Page path = '/sketch'
**Features Till Now:**
1. Hand Drawing
2. Clear Drawing
3. Download Drawing as Image
4. Current Mouse Position
**Screenshots:**
- Header
- Sketch Page
- Drawing
- Downloaded Image
I would Like to contribute more to this. 😊 @smaranjitghose  @anushbhatia 
Thank You!
> [React] Sketch Page Added

- src/components/Header/Header.js
- src/components/Header/Header.module.css
- src/pages/Home/sections/Banner/Banner.module.css
Closes #464 
- Made Top Home Section Responsive
- Quick Box Height to `fit content` (Before, `Sketch` link was not clickable due to this)
- Renamed `headerLinks` to `quickLinks`
I would Like to make `Header` component responsive. If you allow me then I can do that in this same PR.
I have participate in DWOC, SWOC and MWOC.
> Top Home Section Responsive

- src/components/Header/Header.module.css
in PR #473, @sanjay270899  pointed out a flaw. this PR is just to rectify that
**before**
**after:**
> sketch button width fix

- netlify.toml
**update caching policy for _webp_ and _svg_**
gtmetrix showed that having 91days(3months) cache TTL is not sufficient.  Then I further found that it said to have a minimum TTL of 1year. so I updated cache TTL from 3months to 1year
---------
> update caching policy

- public/index.html
Ref https://gtmetrix.com/preconnect-to-required-origins.html
now for downloading contibutors images from https://api.github.com/repos/smaranjitghose/doc2pen/contributors, the browser will establish an early connection with https://api.github.com/ to fetch the resource quickly when `fetch()` is called
adds to #476 
----------
> [performance] added preconnect tag to establish early connection to api.github.com

- src/pages/Editor/containers/editContext.js
- src/pages/Editor/sections/OutputComponent/Output.js
- src/pages/Editor/sections/Settings/Settings.js
there are 2 major updates:
1. Previously on top-settings menu, the toggling between title settings and body settings occurred when we clicked on any one of those button(i,e. clicking on title button twice brought us to body settings which is an undesirable action. It should ideally stay on title settings)...BUT now... clicking on title button only brings us to title settings only. It doesnt switch to body settings like it did before.
2. Now clicking on text-areas also brings us to its respective settings
-------------
> [feature]: Select on text areas to toggle settings mode ( body or title)

- src/pages/Editor/containers/editContext.js
- src/pages/Editor/sections/OutputComponent/Output.js
Added padding to the editor text to look better.
##Before
##After
Would like to work on the second part of this issue.
> Fixed padding to the editor (Issue #658)

- src/pages/Sketch/components/Canvas.js
closes #765 
I removed the current method that changed the canvas background and then i implemented my own method
the problem with current method was that... when the color is selected.. the color is painted all over the canvas (i.e. the drawn stuff is painted with the new background)
BEFORE
AFTER
----------------------------------------
> Canvas background Color Bug fixed

- src/pages/Home/sections/Team/Team.module.scss
the icons wont squeeze now.
--------------------------
closes #793
> [bugfix] Contributor_Section Bug @Home Page

- src/pages/Editor/sections/OutputComponent/Output.module.css
closes #802 
Now the scrollbar is visible on all pages
> Fix: Added Scrollbar on all pages

- src/pages/Sketch/components/Canvas.js
closes #815 
**BEFORE**
**AFTER**
I just learned about how to use `getImageData()` and `putImageData` together to get those objects (pen lines) drawn in realtime.
So this PR just a addition to #791 
---------------------
> enhancement- pen draws on the fly!!

- CONTRIBUTING.md
Updated the revised marking scheme for GSSOC'21 in the CONTRIBUTING file.
closes #821
> Updated marking scheme for GSSOC'21 in CONTRIBUTING file

- src/pages/Editor/sections/OutputComponent/Output.js
Earlier words were split only by space character. Now I've changed the argument passed to the split() method such that words are split on space( ), newline(\n) AND even tab(\t) character, which covers all the commonly used characters that separate words, leading to more accurate word count
> Fixed Word Count: split by space, newline AND tab

- src/pages/Sketch/components/Canvas.js
closes #837 
Now user can set Save File **location** and **name**.
ensured compatibility for different browsers 
-------------------
> "save as" dialog Feature before saving the file

- src/pages/Editor/containers/editContext.js
- src/pages/Editor/sections/OutputComponent/Output.js
closes #798 
The bug in the editor which allowed the user to increase the width to greater values than which that can be contained in the parent element has been fixed!
Before and After Images are attached below.
Before:
After:
> Fixed: Width Bug in the Editor (Closes #798)

- src/pages/Sketch/components/Toolbox/toolbox.module.scss
> [Bugfix]: #881 : Toolbox not scrolling anymore

- package-lock.json
- package.json
- src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx
I have made adequate changes to add tooltips on the review emojis. Kindly review the changes made by me.
Here is a snapshot when we hover over them:
> Tooltips on review emojis

- src/components/Dropdown/Dropdown.jsx
- src/pages/Editor/containers/editContext.js
- src/pages/Editor/sections/OutputComponent/Output.jsx
- src/pages/Editor/sections/Settings/Settings.jsx
- Re-used the dropdown component to create a new one for controlling font-weight in `Settings`.
- Added `bodyFontWeight` as an option to the `editContext` and implemented it in the `Output` section
- Customized the functionality and styling of `DropdownItem` for this new option
- Output when bold is chosen:
- Dropdown Menu for Font Weight:
> Added option for Bold Text in Editor

- src/components/Header/Header.jsx
- on clicking any navigation link, checked if the dropdown menu was open / visible, and if yes, toggled classes using the predefined `drop()` function to hide it
> Hide Dropdown on changing Route / Page on Mobile

- src/pages/Editor/Editor.jsx
- src/pages/Editor/sections/OutputComponent/Output.jsx
- src/pages/Editor/style.module.scss
- Added a state variable for `pageCount`
- Implemented a button that increments `pageCount` by 1
- Implemented a button that decrements `pageCount` by 1 which is disabled if `pageCount!==1`
- Styled both buttons using reactstrap `Button` component
- Repeat the `Output` component `pageCount` number of times
- Passed a `pageNo` prop to the `Output` component, to display page number along with word count
- Styled page number like word count
> Implemented add/remove page buttons, also added page number display

- src/pages/Editor/Editor.jsx
- src/pages/Editor/containers/editContext.js
- src/pages/Editor/sections/OutputComponent/Output.jsx
- src/pages/Editor/style.module.scss
- for downloading, got all the `outputPage` DOM elements.
- looped through all of them and made a dataUrl from each.
- For PNG:
- if there is a single page, exported 1 image with the user given file name
- for multiple pages, exported an image for each page with the name being the user given file name followed by a hyphen and the page number. (example: user chose name doc for a 3 page document, so images generated will be doc-0.png, doc-1.png and doc-2.png)
- For PDF
- created an array of all the dataUrls from all the pages' images
- looped through this array, and added a new page in the pdf for each image
- saved this single pdf by the user given file name
> Implemented Export as both PNG and PDF for Multipage Documents

- src/pages/MediaManip/MediaManip.jsx
Multiple files' simultaneous conversion and download now behaves as expected
(After lots of `console.log()`ing and inspecting, I found that the bug was due to the scoping of canvas element combined with the slow `toDataUrl()` method)
> Fixed Multiple Files Conversion Bug

- src/pages/Editor/Editor.jsx
- src/pages/Editor/sections/OutputComponent/Output.jsx
- Added a state variable for `currentPageNo`
- Implemented a next page button which increments `currentPageNo` by 1 (disabled if `currentPageNo===pageCount`)
- Implemented a previous page button which decrements `currentPageNo` by 1 (disabled if `currentPageNo===1`)
- Only display the Output component if its associated `pageNo=currentPageNo` using a boolean `show` prop
- Made sure that if the user removes the last page while it is active, `currentPageNo` is switched to its previous page
> Implemented Buttons to Toggle between Pages

- src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx
- src/pages/Editor/containers/editContext.js
- src/pages/Editor/sections/OutputComponent/Output.jsx
Either the file download would completely fail or only the active page would be downloaded
The complete file, as expected, is downloaded, and while downloading all the pages are visible. Once download completes, again only the current active page is made visible
> Fixed Multiple Page Exports Bug (Both PNG and PDF format)

- src/pages/MediaManip/DragDrop/DragDrop.jsx
- src/pages/MediaManip/DragDrop/drag-drop.module.scss
- src/pages/MediaManip/MediaManip.jsx
- Dropzone area is always rendered, to allow unlimited file drops
- Styled the file preview to expand horizontally as its content increases till a limit, and then scroll
- Styled the dropzone to take as much space as left beside the file preview but have a minimum width for easy drop
- Without scroll
- With scroll
> Made it possible for user to drag and drop files multiple times

- src/pages/Editor/containers/editContext.js
- When the user chooses to export multiple pages in the Editor as PNG, all the PNGs generated are zipped
- Each PNG file is named `page-x` and the zipped folder is named as the user wanted
> Multiple PNG pages are now Exported as 1 Zipped folder

- src/pages/Editor/Editor.jsx
- Added an `input` of type `number` with range same as the `pageCount`
- Made it reactive so as soon as the user enters a number, the `currentPageNo` state variable is set to that.
> Added Feature to Directly Navigate to any Page by it's Number on Editor Page

- src/pages/MediaManip/DragDrop/DragDrop.jsx
Currently, when PDF files were selected, other image formats still showed up as conversion options. Chosing them would make nothing happen, so no error, but giving false options is bad UX
When a PDF file is selected, user only is only shown the PDF option to merge them
I've added a condition which sets output options to only PDF when a PDF file is dropped by the user
> Bug Fix: PDF files can only be merged, other format options should not show in Output dropdown
