smaranjitghose/doc2pen

assets/css/custom.css, index.html
- I have made the navbar fixed and solved the merge conflict.
=> Navbar fixed and merge conflict

assets/css/custom.css, assets/js/script.js, index.html
now theme can be changed into light and dark. Please review and response.
=> theme_changer_added_by_Varun-28

assets/css/style.css, index.html
Work Done
- Video Optimized and now is in .mp4 format
- Font Changed as Suggested
- Page Layout Changed as Suggested
Improvements
- Footer can be Improved
- Page Theme can be Improved
=> Fixed Homepage

assets/css/style.css, index.html
👇 Work performed :
✔ Made the homepage responsive
✔ The illustration parts are not responsive to mobile phones, these are done
✔ Few texts are not up to the mark, so I just make it look more proper
=> Maded home page Responsive

assets/css/custom.css, assets/js/script.js, editor.html
Now i have set a message line below the text area which show the user remaining characters. 
#10 issue Solved
=> Issue #10 Solved

assets/js/script.js
Characters limit updated to 10k.
=> Enhancement of characters limit to 10k.

assets/js/script.js
Reverts smaranjitghose/doc2pen#42
=> Revert "Enhancement of characters limit to 10k."

assets/css/custom.css, assets/js/script.js, editor.html
Reverts smaranjitghose/doc2pen#40
=> Revert "Issue #10 Solved"

assets/css/style.css, index.html
✔ Made the homepage complete responsive.
✔ Added footer to the appropriate place on the homepage.
=> Complete responsive Homepage

assets/css/contact.css, contact.html
1. Fixed Bugs
2. Removed all useless links
3. corrected cards
review and merge it.
=> corrected contact page

assets/css/contact.css, assets/css/style.css, contact.html, index.html
A site is indeed responsive but there were certain breakpoints that were missed so i tried my best to fix those issues. If this needs any improvement please let me know.
=> Responsiveness of card modified a little bit

404.html, assets/css/style_404.css
=> Solved #70: Added 404 page

assets/js/script.js, editor.html
=> resolved and beautifies code

assets/css/style.css, index.html
Fixes #54 
- I first experimented with couple of new card structure but at the end I finalized the original one but modified it.
- Added shadow property to the cards, colors added according to theme.
- worked on responsiveness of the card structure.
=> Improved card structure

contact.html, editor.html, index.html
Added few meta tags by using open graph to see how our website looks when share on google, facebook, twitter and other social media platforms.
Following tags were added like:
- `<meta` property="og:type" content="">
- `<meta` property="og:url" content="">
- `<meta` property="og:title" content="">
- `<meta` property="og:description" content="">
- `<meta` property="og:image" content="">
Suggest for other tags and optimizations.
Merge to see the changes.
**Needed images for website logo and picture icon on shareable links for various platforms.**
=> #62 added meta tags by using open graph

contact.html, editor.html, index.html
**Added few keywords** 
- Doc2Pen
- assignment generator
- assignment editor
- assignment writing
- text to handwriting
- my text in handwriting
- handwriting text generator
- write assignment online
- convert text to image
- realistic handwriting generator
Suggest changes for these keywords.
Can I start reducing the size of images and other files?
Some `tags `needs correction.
`navbar` in mobile view is also not good.
=> #62 Keywords added

assets/css/style.css, assets/js/main.js, index.html
- I have added a proper responsive navbar.
- The navbar is called dynamically so that we don't have to copy it in every HTML file.
- I have used materialize CSS for the navbar
**Next PR:- I will make a logo (DOC2PEN) using adobe xd as our navbar color is dark so the logo should be white in color.**
@smaranjitghose What say :) ?
ss:-
=> Dynamic Navbar added using materialize css

assets/css/custom.css, assets/js/sketch.js, editor.html
Reverts smaranjitghose/doc2pen#125
=> Revert "Menubar improved"

assets/css/style.css, assets/js/main.js, index.html
@smaranjitghose Have a look :)
ss:
=> Added map (using API) and captcha field

assets/css/style.css, index.html
- I have added the contributor's section (for now only it has dummy data).
@smaranjitghose Have a look at it.
ss:
=> Contributors section added

assets/css/style.css, index.html
- I have added the contributor section (responsive) having dummy data.
@smaranjitghose Have a look.
ss:
=> Contributor section added

assets/css/style.css, assets/js/main.js, index.html
Next PR:- I will add the image and link of each and every team member.
@smaranjitghose Have a look :).
=> Injected the contributor section, added github icon and bug in link button

assets/css/style.css, assets/js/main.js, index.html
@smaranjitghose I have : - 
- linked all the sections to navbar.
- made navbar stick to top on scrolling
- made about section responsive
Please review.
=> nav and about section

assets/css/style.css, index.html
- I have removed the unnecessary CSS and solve the image bug and alignment also.
@smaranjitghose Have a look.
=> About section bug

assets/css/style.css, assets/js/main.js
=> Modified Footer CH20

index.html
Linked the check it out button to the editor page
Fixes #190
=> added link for check out button

assets/js/main.js
Updated links of the contributors.
Fixes #191
=> Contributors.

assets/js/editor.js, editor.html
=> fixed blue color and added option of golden color

assets/js/main.js
navbar was not visible when reaches the banner wavy animation part. As you can see a little text "Editor" on the top right side but it is not clearly visible.
navbar is now visible when reaches the banner wavy animation part.
=> navbar bug fix

assets/js/main.js, index.html
fixes: #196 
@smaranjitghose sir please review.
=> project maintainer details loaded from main.js

assets/css/style.css, assets/js/main.js
Have made the changes I had committed on Issue #222 . Hope that works well!
=> commit on scroll behaviour and button locations

assets/css/style.css, assets/js/main.js, index.html
@smaranjitghose sir i have made the changes requested in #223 and made the project maintainer section responsive . Please review.
=> dynamic details and centered cards

assets/css/style.css, assets/js/main.js, index.html
@smaranjitghose I have solved all the bugs present in the Home page. Have a look.
=> Major Bugs in Home page

assets/css/editor.css, assets/css/style.css
@smaranjitghose sir i have changed the colors of nav and footer. please review.
=> nav and footer colors

assets/css/style.css, index.html
@smaranjitghose I have made the section responsive.
=> Bug in the alignment of contributor section

assets/css/editor.css, assets/js/editor.js, editor.html
@smaranjitghose sir i have added the display for range field values. Please review.
=> range field value display

assets/css/style.css
@smaranjitghose I have added the variant colors accordingly.
=> Colors added accordingly

assets/css/style.css, index.html
- I have added a responsive open source cards section.
SS: ![image](https://user-images.githubusercontent.com/54095539/94943333-29388280-04f5-11eb-809d-a521b4825a7a.png)
=> Open source section added (enhancement)

assets/css/style.css, assets/js/main.js, index.html
- I have done the required changes said for the open-source section and also made it responsive.
ss:
=> Open Source section enhancement (as mentioned)

assets/css/editor.css, assets/js/editor.js, editor.html
Font-size select options is now available in the second nav-bar itself instead of the page body.
1. Code formatting
2. Changes are well commented so that other developers can easily work on the issues
Font size selector was in page body.
Font size selctor is now in second nav-bar
It will resolve issue #197
=> Added font-size select button in nav-bar

assets/js/editor.js, editor.html
=> Made Font Size Functional

assets/css/editor.css, assets/js/editor.js, assets/js/main.js
i have tried and made the menubar to stand out with help of neumorphism effect. Menubar seems to be 3d, as having real like shadow effect.
closes #189
=> Improved the Menubar UI 

assets/css/style.css, assets/js/main.js, index.html
=> Changed contact form UI

editor.html
Fixes #270 : when clicked on download button, it automatically changes the styling of the output page. Now it is fixed.
=> Fixed download button bug

assets/js/editor.js
Fixes: #268 
1. removed unnecessary javascript that was causing the error. (Please view the modified files for reference)
(word count was not updating)
(word count is updating)
=> Fixed word count was not updating

assets/js/editor.js, editor.html
Now the drop down for font size is similar to other drop downs. Also created a new updateFontSize function which updates the font size and also updates the font size value in the menu bar. Compared to old basic select option, this drop down looks more clean.
=> New dropdown for FontSize menu item

assets/css/editor.css, editor.html
Fixes: #271 
Download options added as png, jpg, jpeg and pdf.
=> download options added

assets/css/style.css, assets/js/main.js
1.  Increased the font-size 
2.  Increased the font-weight
3.  decreased opacity
4.  added padding-right
5.  added a transition effect
> code snippet is as below
`.text-big:hover {
font-size: 1.2rem;
padding-right: 0.6rem !important;
transition: 0.2s all ease;
opacity: 0.8;
font-weight: 700;
}`
> On hovering over "contact" it looks like this and the same for others
=> Styled the nav-items on hovering over them

editor.html
=> Converted I-Beam Pointer to Link Pointer

editor.html
Reverts smaranjitghose/doc2pen#295
=> Revert "Converted I-Beam Pointer to Link Pointer"

assets/css/style.css, index.html
I was assigned the issue of "Implementing Map".
I implemented Google maps API and placed the code at the homepage as you needed.
I tested it locally and it works great, but to test at your end you need to enter your API_KEY in the script.
I have used comments properly to ensure proper readability.
Thank you 👍🏻
=> Implementation of maps in homepage

assets/css/style.css, assets/js/main.js
The hover is kept simple with only the shadow when hovered is added.
=> updated the style.css #304

assets/js/editor.js, editor.html
Sir, I added the margin dropdown menu, but for some reason, I am not able to check the code output as the output canvas is not loading. But I believe it works. It's happening even before I have made any changes after forking and cloning I am not able to find the reason behind it if you can give me some suggestions.
I want to keep contributing to code2pen.
=> added margin dropdown menu

assets/css/style.css, assets/js/main.js, index.html
@smaranjitghose I've just added an element which holds the dynamically generated navbar.  Then I added some CSS to that element to fix the issue.
review my version: https://ashuvssut.github.io/doc2pen/
closes #301
=> issue #301 fixed

assets/css/style.css
I have updated the hover effect as suggested
=> updated the hover effect #299

assets/css/editor.css, assets/css/style.css, assets/js/editor.js, editor.html
review link: https://ashuvssut.github.io/doc2pen/editor.html
closes #184
--(I am a SWoC and DWoC participant)
=> [added feature]: added sliders on the edges of the output canvas

assets/css/style.css
Fixes: #339
Solved The map overlapping problem in the "Get in touch section"
***before***
***after***
=> solved map overlapping problem

assets/css/style.css, assets/js/main.js
Now expanded navbar is not mixing with main content
=> Fixed Responsive Navbar #342

assets/css/editor.css, editor.html
review link: https://ashuvssut.github.io/doc2pen/editor.html
closes #330
=> issue #330 fixed

assets/css/painter.css, assets/js/painter.js, painter.html
Canvas color #361
Added Canvas color functionality.
Now users can select canvas color by clicking on the right button and draw anything with the pen tool.
I am attaching some screenshots for showing the new functionality ->
carbseater (DWOC) @smaranjitghose give reviews please Thanks
=> Canvas color

new_file
Deleting the new file @anushbhatia
=> Deleting file

src/App.js, src/components/Header/Header.css, src/components/Header/Header.js
=> navigation bar added in header

src/components/Footer/Footer.css, src/components/Footer/Footer.js
Issue #401 
Added newsletter in footer
=> Added Newsletter in footer

src/pages/Editor/sections/OutputComponent/Output.js
Issue #405 
Implemented Word Count.
=> React: Added Word Count

package-lock.json, src/components/ScrollToTopButton/ScrollToTopButton.jsx, src/components/ScrollToTopButton/style.css, src/index.css, src/pages/Home/index.js
updated:
closes #410
- I have **used a react-bootstrap** button 
- made it into a **reusable react component** so that it can be used in all pages when needed
- button only appear when users has scrolled down more than 50px
- smooth-scroll when clicked on button
-- **(DWoC and SWoC Participant)**
=> scroll to top button component created and implemented in home page

src/components/Dropdown/Dropdown.js, src/pages/Editor/containers/editContext.js, src/pages/Editor/sections/OutputComponent/Output.js, src/pages/Editor/sections/Settings/Settings.js
Issue #406 
Added a dropdown to change font color in the editor.
=> [React] Font Colors Dropdown in Editor

assets/css/editor.css, assets/css/style.css, editor.html, index.html
closes #410 Feature request: Add "ToTop" button on the home page. 
#422 Feature request : Drop down on hover 
***Added back to top functionality***
=> Added back to Top button & DropDown on hover effect

src/App.js, src/components/Preloader/Preloader.jsx, src/components/Preloader/Preloader.module.css
Preview : https://vimeo.com/user132135983/review/504920987/2aa26c23d2
Only CSS used.
closes #424
-- (DWoC and SWoC Participant)
=> preloader implemented

src/pages/Editor/containers/editContext.js, src/pages/Editor/sections/OutputComponent/Output.js
https://user-images.githubusercontent.com/54992097/106383215-ad8b0b80-63ea-11eb-805b-a8bed662082d.mp4
=> Issue#356 Solved Background sheet change

src/pages/Home/sections/OpenSource/OpenSource.module.css
=> REACT: Text Overflow Of Cards

src/pages/Home/sections/Team/Team.js
=> Update Team Section (Fixes #433)

src/pages/Home/sections/Team/Team.js
=> Fixes #434 (Card Images)

src/components/Header/Header.js, src/components/Header/Header.module.css
=> Uniform NavBar and Quick Links (Fixes #438)

src/components/Footer/Footer.css, src/components/Header/Header.module.css, src/pages/Home/index.js, src/pages/Home/sections/About/About.js, src/pages/Home/sections/About/About.module.css, src/pages/Home/sections/Banner/Banner.js, src/pages/Home/sections/Banner/Banner.module.css, src/pages/Home/sections/ContactUs/ContactUs.js, src/pages/Home/sections/ContactUs/ContactUs.module.css, src/pages/Home/sections/OpenSource/OpenSource.module.css, src/pages/Home/sections/SupportUs/SupportUs.js, src/pages/Home/sections/SupportUs/SupportUs.module.css, src/pages/Home/sections/Team/Team.module.css
closes #443 
Now the Home page is made responsive
-- (DWoC and SWoC participant)
=> responsiveness feature for home page

src/pages/Editor/containers/editContext.js, src/pages/Editor/sections/Settings/Settings.js
closes #445
-- DWoC and SWoC participant
=> fixes #445. change x-axis

src/pages/Home/sections/Banner/Banner.js, src/pages/Home/sections/Banner/Banner.module.css
Following changes, I have done
1. Button is now functional and it redirects to the Editor page.
2. Button was not aligned properly I have aligned that.
=> Make button functional and also align.

src/pages/Editor/containers/editContext.js, src/pages/Editor/sections/OutputComponent/Output.js, src/pages/Editor/sections/Settings/Settings.js
closes #454 
-- DWoC and SWoC participant
=> rescaled x-axis adjustment

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
Issue #431 
- Feature to change Pen color and width.
=> Sketch: Pen Color and Width

package-lock.json, package.json, public/index.html, src/pages/Editor/index.js, src/pages/Home/index.js, src/pages/Sketch/Sketch.js, src/seo/MetaComponent.js, src/seo/metaData.js
Closes #462 
- Different `title` for different pages
- Different `description` for different pages
- Different `keywords` for different pages
1. Home Page
2. Editor Page
3. Sketch Page
**metaData**
=> SEO (react-helmet)

src/components/Header/Header.js, src/components/Header/Header.module.css
=> alignment fixed

src/pages/Home/sections/ContactUs/ContactUs.js, src/pages/Home/sections/ContactUs/ContactUs.module.css
currently, when the user clicks on the emoji to send feedback then he/she not able to get what they have selected because they all look the same even after select
Closes #468 
***before***
***What I did?***
I make it interactive so that the user can see what he/she selected.
***after***
***what do I mean by code improvement?***
see in the previous code (currently on the site ) it is just a div containing emojis means it doesn't have any input and validations like only one is selected or something, which means if the user selects one then the form never gets what choice they made.
***old code***
***new code***
***so what I did?***
I make separate div for each and added validations like type=radio which makes sure that only one gets selected at one time and gave them values also so the form …
=> REACT:Added interactive feedback section in contact us form and improve code for the same.

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css
Closes #474 
- Line
- Square
- Circle
- Triangle
- Arrow
- Diamond
Currently not focusing on design. I am thinking to first build some basic features then I will improve the design of the sketch.
=> Sketch Shapes Draw Feature

netlify.toml
now caching for `js`, `css`, `png` enabled for 3months
adds to #476 
-------
user=ashuvssut:score=
=> [feature: performance] added cache control

src/components/Header/Header.js, src/components/Header/Header.module.css
closes #483
Hamburger onClick function is now defined.
-------------
user=ashuvssut:score=
=> Hamburger button now works as desired

src/pages/Sketch/Sketch.js, src/pages/Sketch/Sketch.module.css, src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
Issue #474 
Done:
- Fill Feature
- Stroke Feature
- Opacity Feature
- Improved Arrow Shape
Next:
- I would Like to implement Undo and Redo feature.
- I would Like to redesign the Sketch Layout.
WOC:
- I have participate in `DWOC`, `SWOC`, `MWOC`, and `CrossWOC`.
**Screenshots**
1. Opacity
2. Stroke
3. Fill
4. Improved Arrow Shape
=> Sketch: Fill, Opacity, and Stroke

src/pages/Editor/style.module.css, src/pages/Sketch/Sketch.js, src/pages/Sketch/Sketch.module.css, src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
Closes #474 
Done:
- Revamped the layout of Sketch
- Changed Fill Option into Two
- Added Normal Stroke Option
- Changed opacity for Fill only
Next:
- I would Like to implement Undo and Redo feature.
WOC:
- I have participate in `DWOC`, `SWOC`, `MWOC`, and `CrossWOC`.
**Screenshots**
Before:
Updated:
=> ✨ Revamp Sketch Layout

src/pages/Editor/components/Slider/NumberSlider.js
BUG FIXED: When clicked on decrement button of any settings on editor page-- Error appears 
(----decrement button was not working because of this issue)
closes #536
-------------------------
=> [bugfix]: When clicked on decrement button of any settings on editor page-- Error appears 

src/pages/Sketch/Sketch.module.css, src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
Closes #531 
- Made Undo and Redo Feature
=> Sketch: Undo and Redo

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js
Reverts smaranjitghose/doc2pen#541
=> Revert "Eraser added"

src/components/ScrollToTopButton/ScrollToTopButton.jsx
=> Fixed type error caused by scroll to top button #543

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css, src/pages/Sketch/components/Toolbox/Toolbox.js
Issue #547 
- Added Text Feature
1. Font Size
2. Font Color
3. Font Style
4. Font Family
**GIF**
(Spent my whole night)
=> Sketch: Text Feature

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js
Issue #547
Fill Pattern Feature
=> Sketch: Fill Pattern

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css, src/pages/Sketch/components/Toolbox/Toolbox.js
Closes #556 
- Added Label on Hover
=> Sketch: Label on Hover

src/App.js, src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
Closes #547 
- Improved Custom Fill Option
Before
Now
- Added New Edge Feature
1. Round
2. Bevel
3. Miter
=> Sketch: Improvements and Edge Feature

package-lock.json, src/components/Header/Header.js
This route is very useful for any website specially for mobiles. If anybody want to move to home page, he should have to open drawer and then route. So this is must... in my opinion. 
This is just my starting i see problems and solve them.. Thanks Team
=> Added logo route to home page

README.md
I have tried my best to **retain the cool factor** of the lingo used while also **correcting** any **basic grammatical** errors and **rephrasing** the sentences to sound better. There are still some lines that do not follow the standard rules but they need to be retained so as to keep the cool factor of the project's read me file.
I have also attached the screenshots of the parts where I've made the changes _(excluding some minor ones including whose screenshot would occupy unnecessary space in the PR request)_
.
=> Corrected grammar and rephrased the README.md file

src/pages/Contact/ContactUs.jsx, src/pages/Contact/ContactUs.module.css
=> Removed heading in Contact page

src/pages/Home/sections/About/About.module.css
Resolves #595 
I edited the alignment for the Steps Title and Content, adjusted the layout a bit.
=> Reformatting the Steps Layout #595

src/pages/Contact/ContactUs.module.css
@smaranjitghose pls add gssoc label to this, inked to #598 issue
=> added margin to map

src/pages/Home/sections/OpenSource/OpenSource.module.css
As discussed earlier I added dark colors now they are vibrant with on hovering shadows have also been added which makes it trendy too.
kindly check this out @smaranjitghose and merge my PR.
Thanks
Himika mishra
=> (Re) issue 624 resolved successfully

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Canvas.module.css, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
closes #632 
------------------------
_- I have participated in GSSOC_
=> remove dark mode

src/pages/Editor/containers/editContext.js
Please look into it and merge if it's correct
=> Alerting the user if the uploaded file is not supported

src/pages/Sketch/components/Canvas.module.css
Hi ,
I have tried to increase the size of canvas and remove blue borders (fix #629).Can you please review and if its alright merge it to the main repo.
=> Removed blue border

src/pages/Sketch/components/Canvas.js
closes #656 
--------------------------------
_- I have participated in GSSOC_
=> UNDO/REDO feature's bug fixed

src/pages/Sketch/Sketch.module.css
closes #666 
-----------------------------------
_- I have participated in GSSOC_
=> [bugfix] shaking sketch UI fixed

package-lock.json, package.json, src/pages/Home/sections/About/About.module.css, src/pages/Home/sections/Contact/ContactUs.jsx, src/pages/Home/sections/Contact/ContactUs.module.css, src/pages/Home/sections/OpenSource/OpenSource.js, src/pages/Home/sections/OpenSource/OpenSource.module.css, src/pages/Home/sections/SupportUs/SupportUs.js, src/pages/Home/sections/SupportUs/SupportUs.module.css, src/pages/Home/sections/Team/Team.js, src/pages/Home/sections/Team/Team.module.css
Resolves #660 
Made the headings uniform.
=> Made all home page headings uniform

package-lock.json, package.json, src/pages/Home/sections/About/About.module.css, src/pages/Home/sections/Contact/ContactUs.jsx, src/pages/Home/sections/Contact/ContactUs.module.css, src/pages/Home/sections/OpenSource/OpenSource.module.css, src/pages/Home/sections/SupportUs/SupportUs.js, src/pages/Home/sections/SupportUs/SupportUs.module.css, src/pages/Home/sections/Team/Team.js, src/pages/Home/sections/Team/Team.module.css
closes #701 
shadow adjustment/removal + heading's top-margins added
before
after
-----------------------
=> shadow adjustment/removal +  heading's top-margins  @home page

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js, src/pages/Sketch/components/Toolbox/Toolbox.module.css
=> Add Change Background Feature @Sketch Page #634

src/pages/Home/sections/Contact/ContactUs.jsx, src/seo/metaData.js
**Resolves Issue #678** 
- Updated meta tag to display "Doc2pen"
- Made a change in metadata file
**Before:**
**After:**
=> Fixed meta tag bug @ homepage

src/pages/Home/sections/Team/Team.js, src/pages/Home/sections/Team/Team.module.css
-  Added Border radius to contributors profile images
- Now  all contributers are visible in the homepage 
Resolves #642
=> Changes to Contributors List

package-lock.json, package.json, src/pages/Editor/containers/editContext.js
Now if the user want to import another file, the content of the recent imported file will be removed
=> text append

src/pages/Editor/index.js, src/pages/Home/index.js
I have used useEffect hook in both pages and add functionality to it, whenever the page re-renders the page begins from the top.
Closes #657
=> Editor and Home page are now beginning at the top.

src/pages/404/notFound.jsx, src/pages/404/notFound.module.css
Closes #625
https://user-images.githubusercontent.com/67699840/111788448-19b3c700-88e6-11eb-9024-a2a749cb89af.mov
=> 404 page UI

package-lock.json, src/pages/Editor/containers/editContext.js, src/pages/Editor/sections/OutputComponent/Output.js, src/pages/Editor/sections/OutputComponent/Output.module.css, src/pages/Editor/sections/OutputComponent/Page.css, src/pages/Editor/sections/OutputComponent/Page.js
Added functionality of pangination.
**Features Added-**
- Now we can create multiple pages at the same time and edit them separately.
- We can delete any page
- We can change page through ``next`` and ``prev`` buttons.
- We can download both pfd and image of a single page.
- We can download pdf and image of multiple page at same time.
*Note-* It is having some bug with setting pannel. We need to change the code of setting according to the current change. 
As many things have been included in this PR I would like to suggest opening some other issues to solve these bugs after merging.
close #513
=> Added paginatioin functionality #513

package-lock.json, src/pages/Home/sections/OpenSource/OpenSource.module.scss
#758  size of hovered card fixed
=> #758 size of hovered card fixed

CONTRIBUTING.md, Dockerfile, docker-compose.yml
Fixes Issue #739 
Used docker to remove setup hastle.
=> Fixes Issue #739 : Dockerized the Project

src/pages/Editor/sections/OutputComponent/Output.js, src/pages/Editor/sections/Settings/Settings.js
closes #783 
-------------------------
=> bugfix: Editor editcontext is not switching

src/pages/Home/home.module.scss, src/pages/Home/index.js
closes #779 
--------------------
=> Remove toTop button for smaller screens (when screen-width < 768px)

src/pages/Home/sections/About/About.module.scss, src/pages/Home/sections/Contact/contact-us.module.scss
closes #792 
---------------------------
=> [bugfix] Spacing Bug Mobile View @Home Page

src/pages/Editor/sections/Settings/Settings.js
- Added a new font  as an option to the dropdown Change Styles
- User can now choose to write in the doc with Cedarville Cursive
=> Added Cedarville Cursive Font to the Editor

src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js
closes #767 
------------------------------
=> add stroke+fill color

package-lock.json, src/pages/Sketch/components/Canvas.js, src/pages/Sketch/components/Toolbox/Toolbox.js
- Added a Bi Shape Triangle(Right Angle Triangle) in sketch page shapes.
Closes #744
=> Add Bi Shape Triangle

src/pages/Sketch/components/Canvas.js
closes #787 
you can adjust roughness and stroke width of those shapes too!
shapes with roughness 0 look like computerized shapes
--------------------------------------
=> rough shapes implemented

src/pages/Sketch/components/Canvas.js
closes #636
At last I found a way to store the last state in localstorage
We dont need that user permission thing now😁😁😁
----------------------------
=> persistent canvas state (localstorage)

src/pages/Editor/sections/Settings/Settings.js
=> Changed line-spacing step from 1 to 0.1

src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
=> Constraint on Contact number updated

src/pages/Editor/sections/OutputComponent/Output.js
closes #849 
---------------------
=> removed scrollbar from editor page

README.md
Sir for issue #847 I modified readme file . @smaranjitghose please review this pull request and let me know if there is something I have to change.
=> modified the techstack with logos

src/components/Dropdown/Dropdown.js, src/pages/Editor/sections/Settings/Settings.js
Hey I close pull request #842 due to some long conflict issue and created the same pull request from the master branch, so please check it
=> Show Active Config

src/pages/Editor/sections/Settings/Settings.js, src/pages/Editor/sections/Settings/settings.module.scss
hovering effect added in download file button in editor section in doc2pen
please merge the pr
=> hovering effect added

src/pages/Editor/sections/Settings/settings.module.scss
added hovering effect and color change of hover in import in editor section
=>  added hovering effect and color change of hover in import

README.md
Hello @smaranjitghose  Sir I added no.of forks,stars,pull request,stars and license, repo size tags in the read me file i.e., for issue #888. Please review it an let me know.
=> Added no.of forks,stars,pull request,stars and license, repo size

src/pages/Sketch/components/canvas.module.scss
I have added the hovering effect in the buttons present in the sketch section!
=> added hovering effect in sketch section

src/App.jsx, src/pages/Editor/Editor.jsx, src/pages/Editor/style.module.scss
fixed #880 
I imported the scroll-to-top component to the editor page and made some changes
Can you review it, please? @smaranjitghose @anushbhatia
=> scroll-to-top of editor page

src/App.jsx, src/components/Header/header.module.scss
Fixed #886 
I made the last changes in the Vertical navbar as told me and aligned it in the center with a font size bigger for each link
I am sorry for any mistake made
Can you review it, please ? @smaranjitghose 
Can you add the level3 label that you added in the same issue but in the branch, I closed it, please? @smaranjitghose
=> Vertical-navbar

src/pages/Home/sections/About/About.jsx
Changed 'spent' to 'spend'. 
Resolves #909
=> corrected grammatical error in home page

package-lock.json, src/pages/Home/sections/About/About.jsx, src/pages/Home/sections/About/about.module.scss
I have succesfully added the floating animations in the steps section of the landing page.
Original:
Updated:
=> Added floating animations in images of steps section

src/pages/Sketch/components/Canvas.jsx
The code in PR #901, merged breaking changes in the repo
The feature to load d2ps sketch format was not working because the code for that was overwritten with breaking code.
- The d2ps sketch format loads perfectly
- Now you can load all kinds of images. see screenshot below 
- Removed obsolete code changes. (see code reviews in #901)
- removed unformatted code
PR for issue #869 is dependent on this PR
=> fix bugs in sketch page "save d2ps feature" and "load images feature"

src/App.jsx, src/components/Header/Header.jsx, src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx
=> Fix bug : cannot read property "offsetWidth' of null

public/index.html, src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx
=> [bugfix]: THE icons in icons library do not load unless we hover our mouse on canvas area 

src/App.jsx, src/index.js, src/index.scss, src/pages/404/not-found.module.scss, src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx, src/pages/Home/Home.jsx, src/pages/Home/sections/Banner/banner.module.scss, src/pages/MediaManip/Button/Button.jsx, src/pages/MediaManip/DragDrop/DragDrop.jsx, src/pages/MediaManip/DropDown/DropDown.jsx, src/pages/MediaManip/DropDown/drop-down.module.scss, src/pages/Sketch/components/Canvas.jsx, src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx, src/pages/Sketch/components/Toolbox/Toolbox.jsx, src/scss/_colors.scss, src/seo/MetaComponent.jsx, src/seo/metaData.js
Fixes #938 
(_This PR is under `gssoc21`_)
=> Clean the code

src/pages/Home/sections/About/about.module.scss
Summary of the change and which issue is fixed.
-I have added media queries for mobile devices in the about section.
-I  took care of styling as before.
Fixed  #937 
Attach gif or screenshot for changes.
- Before :
- After :
=> Added media queries for mobile devices

src/components/Header/Header.jsx, src/components/Header/header.module.scss
=> Increased the contacts icons size

src/index.scss
=> Made Text in Textareas Visible on Selection

src/pages/Home/sections/About/About.jsx
Mentioned all the pages (Editor, Sketch and Media Manip) and highlighted the utility of each when making and submitting an assignment
=> Updated Pitch to include all functionalities

README.md
=> Updated the Pitch / Opening Section of ReadMe

src/pages/MediaManip/DragDrop/drag-drop.module.scss, src/pages/MediaManip/DropDown/drop-down.module.scss, src/pages/MediaManip/media-manip.module.scss
=> Made Media Manip Page Responsive

src/components/Dropdown/Dropdown.jsx, src/components/Footer/Footer.jsx, src/components/Header/Header.jsx, src/components/ScrollToTopButton/ScrollToTopButton.jsx, src/pages/404/NotFound.jsx, src/pages/Editor/Editor.jsx, src/pages/Editor/components/DownloadFileModal/DownloadFileModal.jsx, src/pages/Editor/components/Slider/NumberSlider.jsx, src/pages/Editor/containers/editContext.js, src/pages/Editor/sections/OutputComponent/Output.jsx, src/pages/Editor/sections/Settings/Settings.jsx, src/pages/Home/sections/About/About.jsx, src/pages/Home/sections/Banner/Banner.jsx, src/pages/Home/sections/Contact/ContactUs.jsx, src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx, src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx, src/pages/Home/sections/Contact/components/Map/Map.jsx, src/pages/Home/sections/OpenSource/OpenSource.jsx, src/pages/Home/sections/SupportUs/SupportUs.jsx, src/pages/Home/sections/Team/Team.jsx, src/pages/Home/sections/Team/components/FluidCard/FluidCard.jsx, src/pages/MediaManip/Button/Button.jsx, src/pages/MediaManip/DragDrop/DragDrop.jsx, src/pages/MediaManip/MediaManip.jsx, src/pages/Sketch/components/Canvas.jsx, src/pages/Sketch/components/IconLibrary/IconsLibrary.jsx, src/pages/Sketch/components/Toolbox/Toolbox.jsx, src/seo/metaData.js
Because a new eslint config has been added to the project, there were lots of eslint errors across 28 jsx files
Resolves all eslint errors :
- convert all linebreaks from `\r\n` to `\n`
- converted all spaces to tabs (indent warns)
- other minor eslint errors
closes #998
=> Resolve eslint errors

src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.jsx, src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
- add form validation messages
- add Regex for validation
- add other important form attributes
closes #1010
=> Experience Form Validation + Regex + other Input tag attributes

src/pages/Home/sections/About/About.jsx
i have fixed the issue #994 concerning the bug in the documentation. I hope it's fine.
=> Fixes #994

.eslintrc.js, src/pages/Editor/containers/editContext.js, src/pages/MediaManip/MediaManip.jsx
- Restore eslint rules that were originally removed from PR #995
- resolve errors that show up from dev server
closes #1006
=> Restore eslint rules + resolve errors that show up from dev server

.github/workflows/prettier_action_on_PR_and_push.yml
=> add prettier action

.eslintrc.js, .prettierignore, .prettierrc.js
=> Add Linters config files

src/pages/MediaManip/MediaManip.jsx
=> Updated Page Heading to File Converter

src/pages/Home/sections/Contact/components/Map/Map.jsx, src/pages/Home/sections/Contact/components/Map/map.scss
Features added
- [Animated Panning](https://react-leaflet.js.org/docs/example-animated-panning)
- Map placeholder added - Placeholder will show only when it is detected that JS is disabled or map is not loading.
=> New map features

src/pages/Sketch/components/Toolbox/toolbox.module.scss
=> fix: colorPicker popup's z-index

.eslintrc.js, package-lock.json, src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
Fixes Issue #1057 
I added a feature without back end with which user would be sent to a fresh new page on clicking Send button where the message is displayed as "Thank you We received your submission , Return ". Also on clicking to Return button of that fresh new page, user is redirected to home page.
https://user-images.githubusercontent.com/61961107/123539142-dc1cd080-d755-11eb-80a9-78ffab50b096.mp4
=> User sent to fresh new page upon contact form submission without Backend

src/pages/MediaManip/MediaManip.jsx, src/seo/metaData.js
Resolves #1067 
It changed the title screen
=> Added MetaComponent and metadata for media manip

.eslintrc.js, package-lock.json, src/pages/MediaManip/DragDrop/DragDrop.jsx, src/pages/MediaManip/DragDrop/drag-drop.module.scss
=> MediaManip Upload Box UI Update

CONTRIBUTING.md
Fixed a typo in the 39 line of the CONTRIBUTING.md file, 
so instead the double add "Add add" it will be one "Add".
=> Fixed a typo in the 39 line of the CONTRIBUTING.md file
